<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Query\Expression;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * What a supporter holds up to say "stop writing to me".
 *
 * D-16(a). The blast module can now mail a campaign's whole list and offers no
 * way out, which §1 names as the cost of sending mail at all, independent of
 * any compliance regime. A supporter has no account and no session, so the link
 * in the message has to carry its own authority, and this column is it.
 *
 * **A random per-supporter token rather than a signed URL, and the reason is a
 * measurement rather than a preference.** A signed URL is taken over the
 * platform-wide APP_KEY, so the only thing separating one campaign's link from
 * another's is whatever campaign-shaped text is inside the signed string.
 * Measured with two campaigns, one of them holding a second hostname:
 *
 *   - A bare `signed` signature covers the absolute URL, host included. It is
 *     refused on the *same campaign's* second hostname -- so a campaign that
 *     later adds its own branded address breaks every unsubscribe link it has
 *     already mailed, silently and permanently.
 *   - A `signed:relative` signature covers only the path. It validates on
 *     *another campaign's* host -- and because supporter ids restart at 1 in
 *     every campaign, one campaign's link unsubscribes another campaign's
 *     supporter. That is L-27's family arriving at a URL: a value trusted
 *     across a boundary it is not unique within.
 *
 * Neither arm is safe. A token has no such split, because its scope is not a
 * string the platform signs -- it is **the campaign's own database**. A token
 * minted in one campaign, presented on another campaign's host, finds no row,
 * for the same reason a supporter does not: the row is in another database.
 * That is DEC-1's guarantee, already proven five separate times in this
 * project, rather than a new mechanism nobody has exercised.
 *
 * **Deferral 19 therefore does not fire** (no signature, so no per-campaign key
 * question), and **deferral 3 does not fire** either: a mailed link still names
 * a hostname, so a campaign that stops answering there breaks it -- which is
 * true of every link in every email ever sent -- but the signature-specific
 * half, a link *refused* on a host that legitimately belongs to the campaign,
 * does not exist here. The mechanism choice is what kept both shut.
 *
 * **Generated by a database default, never by application code, and this is the
 * load-bearing decision in the file.** A model `creating` hook is the obvious
 * home and is wrong: measured, it fires for `Supporter::create()` and does
 * **not** fire for the importer's `Supporter::query()->upsert()`, which is how
 * every supporter of any real campaign arrives. That is the Blueprint's "a cast
 * on a column nothing writes through the model is decorative" arriving at a
 * generator, and the consequence would be an imported supporter with no way to
 * unsubscribe -- discovered by the person who could not get out. A column
 * default is the one mechanism no writer escapes: Eloquent's creator, the
 * importer's upsert and a raw query-builder insert were each measured to
 * receive their own value.
 *
 * **Supporters who predate this column need no data migration, which was
 * measured rather than assumed.** `gen_random_uuid()` is volatile, so
 * PostgreSQL evaluates it per row when adding a NOT NULL column with it as the
 * default: three pre-existing rows came back with three distinct tokens. The
 * cost of that is a full table rewrite while the column is added, which is a
 * one-time exclusive lock proportional to the list -- trivial at demo scale and
 * worth knowing about for a campaign with a quarter of a million supporters.
 *
 * `gen_random_uuid()` is core PostgreSQL (measured on 18.1) and needs no
 * extension, which is why it can be a default at all. 122 bits of randomness is
 * not guessable, and the route in front of this column is metered besides.
 *
 * **A `uuid` column rather than a string, paired with a route constraint.** The
 * type is the honest one and the database can then never hold a value that is
 * not a token. It has one sharp edge, measured: a lookup for a malformed token
 * against a `uuid` column raises SQLSTATE 22P02 rather than matching no rows,
 * so a stranger typing nonsense into the address bar would get a 500 -- and the
 * exception message inlines the offending binding, which is Phase 1's
 * QueryException finding on a route anybody can reach. The route carries
 * `->whereUuid()` so the router answers 404 before any query is built, and a
 * test pins both halves.
 *
 * **Unique, because a shared token is a link that unsubscribes an arbitrary
 * one of two people.** A collision between two random UUIDs is not a thing that
 * happens; this says so in the schema rather than trusting it, for the same
 * reason `blast_recipients` states its own claim there.
 *
 * **D-10 is asked here for the third time and answered by running a deletion.**
 * The token is a credential, so where it lives matters -- and it lives on
 * `supporters`, the one table an erasure already reaches, so it goes with the
 * row. Measured, not read: deleting the supporter left zero rows carrying that
 * id. D-10 is not weakened and needs no amendment.
 *
 * Frozen, like every migration here: no value is read out of application code,
 * so this produces the same schema for a campaign provisioned today and one
 * provisioned after any future edit.
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('supporters', function (Blueprint $table) {
            $table->uuid('unsubscribe_token')
                ->default(new Expression('gen_random_uuid()'));

            $table->unique('unsubscribe_token');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('supporters', function (Blueprint $table) {
            // The index belongs to the column and goes with it.
            $table->dropUnique(['unsubscribe_token']);
            $table->dropColumn('unsubscribe_token');
        });
    }
};
