<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Query\Expression;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * One act of a campaign admitting somebody who is not yet an operator of it.
 *
 * D-54, consuming D-53's Axis 1 (i): a person is authorized to become an
 * operator by a row in the campaign's own database naming who was invited,
 * resolved by a credential in a link. This is that row. It lives in the tenant
 * migration set for the reason operators and their trail do (D-1) -- an
 * invitation is one campaign admitting somebody to itself, and it is also what
 * makes the credential safe: a token minted here matches no row in any other
 * campaign because the row is in another database, which is the property D-46
 * re-ran for the per-recipient link and Step 1 re-ran again for a stand-in
 * invitation (1 row in Harbor, 0 in Ridge, both rows id 1, no central table).
 *
 * **What this table is not, said first, because all three of the obvious
 * precedents in this campaign's database answer a different question.**
 * `supporters.unsubscribe_token` is a credential every row must have, so it is
 * NOT NULL with its default in one statement. `blast_recipients.link_token` is
 * a credential minted per copy that must not outlive its subject, so it is
 * nullable and a trigger removes it. `unsubscribes` is an events table with no
 * status and deliberately no subject key, so nothing there names anybody from
 * the moment it is written. An invitation is none of those: its whole content
 * is an address belonging to somebody who is not a supporter, not yet an
 * operator, and may never become either -- so the property that made
 * `unsubscribes` free of the erasure question is exactly the property this
 * table cannot have. That is asked by running a deletion rather than by
 * analogy, and D-55 records what the deletion found.
 *
 * **A pending invitation is a claim about the future and an accepted one is a
 * record of the past, and one table serves both deliberately.** D-47 measured
 * that conflation for outcomes and refused it, so the reason this is not the
 * same mistake has to be stated rather than assumed. There, a record of events
 * was being asked a question about current state, and the remedy was to keep
 * `supporters.subscription_status` as the single answer to "may this person be
 * written to". Here there is no second table that already answers the state
 * question: `users` answers "is this person an operator", and nothing at all
 * answers "who admitted them" -- because the trail cannot. `OperatorAuditObserver`
 * takes its actor from `Auth::user()` and an invited person accepting their
 * own invitation is unauthenticated at the moment the operator row is created,
 * which is precisely why `audit_entries.actor_id` is nullable and says so in
 * its own migration. So the row must survive being accepted, and the reason is
 * not convenience: D-53 refused shape (iii), a rule such as an allowed email
 * domain, *because* it "cannot name who admitted whom". A row deleted on
 * acceptance would lose the one property the chosen shape was chosen for.
 *
 * **What the row holds, each column answering a question somebody asks.**
 *
 * `email` -- who was invited. Forced by D-53's refusal of shape (iv), an
 * out-of-band code, which was refused because it "cannot record who it was
 * meant for". An invitation that does not name a person is that shape again
 * wearing a row.
 *
 * `role` -- with what authority. An invitation that cannot say would defer the
 * decision to a promotion surface, and there is none: `roleForNewOperator()`
 * grants Owner only while `User::query()->exists()` is false, so a campaign
 * that loses its Owner while any other operator remains is ungovernable
 * forever (Step 1's finding B). The column is the one path by which a second
 * Owner can exist at all. It is `string` with a hardcoded default rather than a
 * database enum, for the reason `users.role` and `audit_entries.event` are:
 * this migration runs again for every campaign at whatever date that campaign
 * is provisioned, so a constraint or default read out of application code
 * would give campaigns created after an edit a different schema from the ones
 * already provisioned. The literal and `OperatorRole::default()` are pinned to
 * each other by a test instead, which is what keeps this file frozen. The
 * default is the *least* authority for the reason the `users.role` default is:
 * a creator that forgets to say produces the least privileged operator rather
 * than an over-privileged one.
 *
 * `token` -- may this link still be used. Forced by D-53's Axis 1 (i). A `uuid`
 * generated by a column default, for the two reasons D-16(a) recorded: the
 * type is the honest one, so the database can never hold a value that is not a
 * token, and a default is the one generator no writer escapes. **Nullable, and
 * the null is the whole of the single-use property.** A spent invitation holds
 * no credential, which makes "pending" a fact about the row rather than a
 * status column somebody has to remember to read -- the same move `unsubscribes`
 * made by refusing a status column outright.
 *
 * **The default arrives in the same statement, and the contrast with
 * `blast_recipients.link_token` is the reason to say so.** There, a nullable
 * column with a volatile default had to be added bare and then given its
 * default, because adding both at once fills every row that already exists and
 * "null" had to keep meaning "this copy predates per-copy links". A `create`
 * has no rows that already exist, so there is nothing for the default to fill
 * and nothing for the second statement to protect. The two-statement dance is
 * a remedy for a hazard this table does not have.
 *
 * `invited_by_id` and `invited_by_label` -- who did this, and who did this
 * readably once they are gone. Both nullable and **neither is a foreign key**,
 * which is `audit_entries`' shape adopted rather than reinvented, for its
 * reasons exactly. A constraint on the inviter would delete the record of the
 * admission along with the Owner who made it, or refuse to let that Owner go;
 * and the label is captured at write time because by the time anybody reads
 * this row, the operator it names may not exist. They are nullable for the
 * reason `audit_entries.actor_id` is nullable -- an invitation is not always
 * made on somebody's authority. D-53's Axis 3, *where a campaign's first Owner
 * comes from*, is raised and unresolved, and one of its named shapes is
 * provisioning minting the first invitation, which has no operator to name.
 * NOT NULL here would decide that axis by accident, in a schema step that does
 * not hold the question.
 *
 * `accepted_at` -- did they come, and when. Not redundant with a null token:
 * the token says the link is spent, and only this says the row produced an
 * operator rather than being withdrawn. **There is deliberately no pointer to
 * the operator it produced.** An invitation is a record of an act aimed at an
 * address, not a pointer to a row -- the same reason `audit_entries` captures
 * `subject_label` instead of joining -- and a key would either take the record
 * away with the operator (cascade) or leave a dangling null that answers
 * nothing the address does not. It also keeps this table clear of the hazard
 * `CentralSchemaTest` records against itself: `blasts` and `segments` carry a
 * foreign key to `users`, so misfiling either migration centrally kills every
 * test in that file before an assertion runs. This table has no such key, so
 * misfiling it migrates cleanly and the central schema's own exact list of
 * tables reports the difference -- measured by putting a copy of this
 * migration into the central set, rather than reasoned from the absence of a
 * constraint.
 *
 * **No expiry column, and that is a decision rather than an omission.** A
 * lifetime is a comparison against `created_at` at read, which costs no column
 * and -- decisively -- no schedule: D-49's precedent is that enforcement at
 * read costs nothing, while a pruning command would be a fifth declaration in
 * an application where nothing runs the four that exist (deferral 17, which
 * this file is forbidden to answer with a fifth inert declaration). Deriving
 * rather than storing also means shortening the window shortens the
 * invitations already in flight, which is the direction a credential should
 * fail in. **Whether there is a window at all, and how long, is D-59's at Step
 * 5**, which is the step that can price it; this file only establishes that
 * the schema owes nothing either way. An expired invitation is still a row,
 * because somebody was invited and did not come and that is a fact a second
 * Owner should be able to see.
 *
 * **Both timestamps, unlike `audit_entries` and `unsubscribes`, and for the
 * same reason those two have only one.** Each of them omits `updated_at`
 * because the row is never revised. This row is revised, exactly once, when it
 * is accepted -- and may be revised again if a campaign re-invites somebody
 * whose invitation it withdrew. Saying so in the schema is the same honesty
 * those files showed by refusing the column.
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('operator_invitations', function (Blueprint $table) {
            $table->id();

            // The person, as an address. This is the column that makes the
            // table personal data about somebody who may have no other row
            // anywhere in this campaign, which is what D-55 is about.
            $table->string('email');

            // Deliberately the literal rather than OperatorRole::default(), and
            // a plain string rather than a database enum. See the note above:
            // this migration runs once per campaign at that campaign's own
            // provisioning date, so anything it reads out of application code
            // becomes schema that differs between campaigns on one deploy.
            $table->string('role')->default('staff');

            // The credential, and its absence is what "already used" means.
            //
            // One statement, because a `create` has no existing rows for a
            // volatile default to fill -- the hazard that forced
            // `blast_recipients.link_token` into two statements does not exist
            // here. Explicitly inserting null still overrides the default,
            // which is what spending the invitation will do.
            //
            // Unique, because a shared credential admits an arbitrary one of
            // two people and no reader of either row could tell which -- the
            // same claim `supporters.unsubscribe_token` states in the schema
            // rather than trusting. Nulls do not conflict in a unique index, so
            // any number of spent invitations sit here without collision.
            $table->uuid('token')->nullable()->unique()->default(new Expression('gen_random_uuid()'));

            // Who admitted them. No foreign key, by the same argument
            // `audit_entries` makes for `actor_id`: the record has to outlive
            // the operator who made it. Nullable because an invitation is not
            // always made on an operator's authority -- D-53's Axis 3 is open,
            // and one of its shapes has provisioning mint the first one.
            $table->unsignedBigInteger('invited_by_id')->nullable();
            $table->string('invited_by_label')->nullable();

            // When they came, and null while they have not. The row is not a
            // pointer to the operator it produced; see the note above.
            $table->timestamp('accepted_at')->nullable();

            $table->timestamps();
        });

        // **At most one *live* invitation per person, and the partial index is
        // what lets that be true without making a person un-invitable
        // forever.**
        //
        // A plain unique index on the address would refuse to invite somebody
        // a second time after they left the campaign, which is an ordinary
        // thing for a campaign to do. Scoped to rows that still hold a
        // credential, it says the thing actually worth saying: a campaign
        // cannot have two outstanding invitations to one person granting
        // possibly different authority, where whichever link they happen to
        // click decides what they become.
        //
        // On lower(email) for D-8's reason -- casing is not part of who
        // somebody is, and a campaign treating Jean@Example.test and
        // jean@example.test as two people has failed at exactly the variation
        // real address lists are full of.
        //
        // **This is stricter than `users`, measured rather than assumed**, and
        // the asymmetry is recorded rather than quietly matched:
        // `users.email` carries the schema builder's plain `unique()`, so a
        // campaign may today hold two operators whose addresses differ only in
        // casing. That is the looser of the two and it is not this migration's
        // to change.
        //
        // Raw DDL because the schema builder can express neither half: a unique
        // *constraint* rejects an expression (42601) and the promotion path
        // rejects it again (42809), which is what drove
        // `supporters_email_unique` to raw DDL, and `unique()` has no partial
        // form at all. Through the builder's own connection rather than
        // DB::statement(), so the index cannot land centrally while the table
        // it constrains went to a campaign.
        Schema::getConnection()->statement(
            'create unique index "operator_invitations_live_email_unique" '
            .'on "operator_invitations" (lower(email)) where "token" is not null'
        );

        // **A spent invitation must not still hold a usable credential, and the
        // schema says so rather than the one writer.**
        //
        // This is the constraint `blast_recipients.link_token` wanted and could
        // not have. There, `supporter_id is not null or link_token is null` was
        // written, measured and refused, because the foreign key's own SET NULL
        // violates it -- so the erasure is refused outright and the error's
        // DETAIL prints the credential into whatever log records it. A trigger
        // had to be used instead. This table has no referential action to
        // violate the constraint, so the constraint is available, and it is the
        // better of the two: a trigger that silently nulls hides a writer that
        // got it wrong, while a constraint that refuses names it.
        //
        // What it is worth is concrete rather than theoretical. The invitation
        // mail carries the credential, and `.env.example` still ships
        // MAIL_MAILER=log, which writes whole messages into the application
        // log. A link that is spent and still resolves is a live credential
        // sitting in a log file.
        //
        // Stated at its true strength, the way `blast_recipients_sent_or_failed`
        // states its own: this forbids the contradiction, not the third state.
        // A row with neither a credential nor an acceptance is legal and
        // meaningful -- it is an invitation somebody withdrew. Whether a
        // withdrawal leaves such a row or removes it is D-57's at Step 4, and a
        // biconditional here would settle that by accident.
        Schema::getConnection()->statement(
            'alter table "operator_invitations" add constraint "operator_invitations_spent_token_removed" '
            .'check (not ("accepted_at" is not null and "token" is not null))'
        );
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // The index and the constraint belong to the table and go with it.
        Schema::dropIfExists('operator_invitations');
    }
};
